var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/books/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f287868e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f0343b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f76e98d3._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__76927d8c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__15cb59d8._.js")
R.c("server/chunks/ssr/_8e35cbd0._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.c("server/chunks/ssr/_70c78ecd._.js")
R.m(79766)
R.m(53023)
module.exports=R.m(53023).exports
