var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/photobook/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9692e6ac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f0343b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f76e98d3._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__76927d8c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__91efa692._.js")
R.c("server/chunks/ssr/_c91f20d5._.js")
R.c("server/chunks/ssr/_70c78ecd._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.m(4400)
R.m(43663)
module.exports=R.m(43663).exports
